# Generated by Django 3.1.3 on 2020-11-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='authCode',
            field=models.IntegerField(default=36749),
            preserve_default=False,
        ),
    ]
